---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/mvilain/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/vilain/dotfiles
dotfiles_files:
  - .aliases
  - .exports
  - .exrc
  - .inputrc
  - .vimrc
  - .zshrc
  - robbyrussell.zsh-theme
  - xero

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - aria2
  - autoconf
  - autoconf-archive
  - automake
  - bash
  - bison
  - brotli
  - btop  # also installs isl, libmpc, gcc
  - ca-certificates
  - cfssl
  - cmake
  # - cmake-docs # 11/2/23 python-packaging won't compile python 3.12 version
  - coreutils
  - curl
  - dateutils
  - dc3dd
  - docker-machine
  - docutils
  - envconsul
  - findutils
  - fping
  - fzf
  - gawk
  - gdbm
  # https://github.com/prasmussen/gdrive/issues/663
  # - gdrive  2/1/2023 broken: google deprecated authetication method
  - gettext
  - git
  - gitup
  - git-interactive-rebase-tool
  - glances
  - gmp
  - go
  - go-bindata
  - hashicorp/tap/boundary
  - hashicorp/tap/consul
  - hashicorp/tap/nomad
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - hashicorp/tap/vault
  - hashicorp/tap/waypoint
  - helm
  - htop
  - intltool
  - jq
  - kops
  - kubernetes-cli
  - libevent
  - libidn2
  - libnghttp2
  - libpng
  - libssh2
  - libtool
  - libunistring
  - libusb
  - libyaml
  - logrotate
  - lynx
  - lzip
  - m4
  # - mcrypt  10/28/22 deprecated
  - mhash
  - minikube
  - mpdecimal
  - mpfr
  - ncurses
  - nginx
  - nmap
  - oniguruma
  - openldap
  - openssl@1.1
  - openssl@3
  - p7zip
  - pcre
  - pcre2
  - pkg-config
  - popt
  - python@3.10
  - python@3.11
  - python@3.12
  - rbenv
  - rclone
  - kapitainsky-rclone-browser
  - readline
  - rtmpdump
  - ruby-build
  # - ruby@2.7 # 5/15/23 ruby@2.7 deprecated
  # https://forge.rust-lang.org/infra/other-installation-methods.html
  # - rust # 3/16/23 use 'curl https://sh.rustup.rs -sSf | sh' instead of brew
  - six
  # - sphinx-doc   # 11/2/23 requires python-packages which won't install on 10.15
  - sqlite
  - ssh-copy-id
  - staticcheck
  - telnet
  - telnetd
  - terraform-docs
  - terragrunt
  - tldr
  - tnftp
  - tnftpd
  - tree
  - utf8proc
  - vagrant-completion
  - watch
  - webp
  - wget
  - xz
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh
  - zstd

homebrew_taps:
  - buo/cask-upgrade
  - homebrew/core
  - homebrew/cask
  - hashicorp/tap

homebrew_cask_appdir: /Applications

# the following apps have been updated beyond 10.13
# and require at minimum Moneterrey (MacOSX 12)
homebrew_cask_apps_15:
  - 1passwword
  - alfred
  - appcleaner
  # - calibre       # 11/17/23 7.0 on 12+, 6.29 on Ventura, 6.11 on Catalina
  - chronycontrol   # 8/18/23 1.4.11 installs and starts daemons correctly
  - forklift        # 12/2/23 4.0.5 installs on 12+
  - google-drive    # 10/19/22 discontinued 10.13 support on 10/21/22
  # - grandperspective # 3.3 last version that supports 10.15 7/16/23
  - kdiff3          # 1.9.5 last version that supports 10.13 12/18/22
  - launchcontrol   # 10/16/23 2.5 working
  # - microsoft-teams # 10/31/23 new teams runs on BigSur+ (don't bother with teams)
  - mullvadvpn      # 7/4/23 2023.4 says it only installs on BigSur+
  - netiquette
  - profind         # 12/24/22 1.8 last version that supports 10.13
  - steermouse      # 10/19/22 5.6 last version that supports 10.13
  - torguard        # 3/8/23 4.8.14 supports 10.13; 4.8.15 installs 4.8.14 on 10.13; 4.8.16 just fails
  - typora          # 3/8/23 1.5.8 last version that supports 10.13
  - vagrant         # 10/26/22 2.3 doesn't run on 10.13 -- missing gem google-protobuf
  - viscosity
  - whatsyoursign   # 5/26/23 v2.1 won't install
  - xrg             # 10/31/23 v3.2.1 runs on BigSur+

# the following apps work on 10.15 as of 10/2/23
homebrew_cask_apps:
  - 1password-cli
  - a-better-finder-attributes
  - a-better-finder-rename
  - affinity-designer
  - affinity-photo
  - affinity-publisherspek
  - anki
  - app-tamer
  - audacity
  - audiobook-builder
  - authy
  - balenaetcher
  - brave-browser
  - busycal
  - busycontacts
  - coconutbattery
  - commander-one
  - cyberduck
  - dbeaver-community
  - default-folder-x
  - dropbox
  - easyfind
  - eloston-chromium
  - etrecheckpro
  - exiftool
  - firefox
  - fliqlo
  - floorp
  - github
  - gitup
  - google-chrome
  - google-web-designer
  - go2shell
  - gotomeeting
  - graphicconverter
  - icollections
  - imazing
  - intellij-idea
  - istat-menus
  - jitsi-meet
  - joplin
  - keka
  - keyboard-maestro
  - knockknock
  # - macfuse # prereq for Veracrypt and docker
  - mdimagesizemdimporter
  - mediahuman-youtube-downloader
  - meteorologist
  - neofinder
  - ngrok
  - nvalt
  - opera
  - pacifist
  - rar
  - scrivener
  - skype
  - sloth
  - sublime-merge
  - sublime-text
  - superduper
  - sync
  - Taskexplorer
  - tg-pro
  - the-unarchiver
  - tor-browser
  - usenapp
  - vlc
  - vuescan
  - webex # 6/18/23 43.6.x downloaded from web site linked with wrong libraries...use brew to update
  - whatroute
  - xquartz
  - youtube-to-mp3
  - zenmap
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
# tldr is an abbreviated man page https://github.com/tldr-pages/tldr
pip_packages:
  - ansible
  - ansible-core
  - ansible-lint
  - asn1crypto
  - astroid
  - certifi
  - cffi
  - entrypoints
  - flake8
  - importlib-metadata
  - isort
  - lazy-object-proxy
  - mccabe
  - pip
  - platformdirs
  - protobuf
  - pycodestyle
  - pycparser
  - pyflakes
  - pylint
  - setuptools
  - six
  - Sphinx
  - sphinxcontrib-napoleon
  - toml
  - typed-ast
  - typing-extensions
  - urllib3
  - virtualenv
  - wheel
  - wrapt
  - yamllint
  - xattr
  - zipp
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "Alignment"
  - "Ansible"
  - "AutoFileName"
  - "BracketHighlighter"
  - "ChangeQuotes"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "Git"
  - "GitGutter"
  - "GitHub Flavored Markdown Preview"
  - "GitOpenChangedFiles"
  - "Golang Build"
  - "Highlight Trailing Whitespace"
  - "INI"
  - "Jinja2"
  - "Markdown Extended"
  - "MarkdownPreview"
  - "Package Control"
  - "Pretty JSON"
  - "Puppet"
  - "SublimeLinter"
  - "SublimeLinter-contrib-puppet-lint"
  - "SublimeLinter-contrib-staticcheck"
  - "SublimeLinter-contrib-yamllint"
  - "Terraform"
  - "Theme - Brogrammer"
  - "Theme - Monokai Pro"
  - "TrailingSpaces"
  - "Typora Markdown App (OSX)"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
