---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/mvilain/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/vilain/dotfiles
dotfiles_files:
  - .aliases
  - .exports
  - .exrc
  - .inputrc
  - .vimrc
  - .zshrc
  - robbyrussell.zsh-theme
  - xero

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - aria2
  - autoconf
  - autoconf-archive
  - automake
  - bash
  - bison
  - hashicorp/tap/boundary
  - brotli
  - ca-certificates
  - cfssl
  - cmake-docs
  - hashicorp/tap/consul
  - coreutils
  - curl
  - dateutils
  - dc3dd
  - docker-machine
  - docutils
  - envconsul
  - findutils
  - fping
  - gawk
  - gdbm
  - gdrive
  - gettext
  - gh
  - git
  - git-interactive-rebase-tool
  - glances
  - gmp
  - go
  - go-bindata
  - helm
  - htop
  - intltool
  - jq
  - kops
  - kubernetes-cli
  - libevent
  - libidn2
  - libnghttp2
  - libpng
  - libssh2
  - libtool
  - libunistring
  - libusb
  - libyaml
  - logrotate
  - lzip
  - m4
  # - mcrypt  10/28/22 deprecated
  - mhash
  - minikube
  - mpdecimal
  - mpfr
  - ncurses
  - nginx
  - nmap
  - hashicorp/tap/nomad
  - oniguruma
  - openldap
  - openssl@1.1
  # - openssl@3
  - p7zip
  - hashicorp/tap/packer
  - pcre
  - pcre2
  - pkg-config
  - popt
  - python@3.10
  - rbenv
  - rclone
  - readline
  - rtmpdump
  - ruby-build
  - ruby@2.7
  - six
  - sphinx-doc
  - sqlite
  - ssh-copy-id
  - staticcheck
  - telnet
  - telnetd
  - hashicorp/tap/terraform
  - terraform-docs
  - terragrunt
  - tmux
  - tnftp
  - tnftpd
  - tree
  - utf8proc
  - vagrant-completion
  - hashicorp/tap/vault
  - watch
  - hashicorp/tap/waypoint
  - webp
  - wget
  - xz
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - youtube-dl
  - zsh
  - zstd

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - hashicorp/tap

# alfred 5 works best on MacOS 10.14 even though it installs OK
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password-cli
  - a-better-finder-attributes
  - a-better-finder-rename
  # - alfred
  # - anki  2.1.55 requires 10.14
  - another-redis-desktop-manager
  - app-tamer
  - audacity
  - audiobook-builder
  - authy
  - balenaetcher
  - brave-browser
  - busycal
  - busycontacts
  - chronycontrol
  - cmake
  - coconutbattery
  - cyberduck
  - dbeaver-community
  - default-folder-x
  - dropbox
  - eloston-chromium
  - etrecheckpro
  - exiftool
  - firefox
  - fliqlo
  - forklift
  - github
  - gitup
  - google-chrome
  # - google-drive  # 10/19/22 discontinued 10.13 support on 10/21/22
  - google-web-designer
  - gotomeeting
  - grandperspective
  - graphicconverter
  - imazing
  - intellij-idea
  - istat-menus
  - jitsi-meet
  - joplin
  - kdiff3
  - keka
  - keyboard-maestro
  - knockknock
  # - launchcontrol # 11/01/22 V2.0 runs on 10.14
  - macfuse
  - mdimagesizemdimporter
  - mediahuman-youtube-downloader
  - meteorologist
  - microsoft-teams
  # - mullvadvpn
  - neofinder
  # - netiquette
  - ngrok
  - nvalt
  - opera
  - pacifist
  - profind
  # - qlimagesize
  - rar
  - scrivener
  - skype
  # - steermouse # 10/19/22 5.6 last version that runs on 10.13
  - sublime-merge
  - sublime-text
  - superduper
  - sync
  - Taskexplorer
  - tg-pro
  - the-unarchiver
  - tor-browser
  - torguard
  - typora
  - usenapp
  - vagrant # 10/26/22 2.3 doesn't run on 10.13 -- missing gem google-protobuf
  - veracrypt
  - vlc
  - vuescan
  - webex
  - whatroute
  - whatsyoursign
  - xquartz
  - xrg
  - youtube-to-mp3
  - zenmap
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - ansible
  - ansible-core
  - ansible-lint
  - asn1crypto
  - astroid
  - certifi
  - cffi
  - entrypoints
  - flake8
  - importlib-metadata
  - isort
  - lazy-object-proxy
  - mccabe
  - pip
  - platformdirs
  - protobuf
  - pycodestyle
  - pycparser
  - pyflakes
  - pylint
  - setuptools
  - six
  - Sphinx
  - sphinxcontrib-napoleon
  - toml
  - typed-ast
  - typing-extensions
  - urllib3
  - virtualenv
  - wheel
  - wrapt
  - yamllint
  - xattr
  - zipp
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "Alignment"
  - "Ansible"
  - "AutoFileName"
  - "BracketHighlighter"
  - "ChangeQuotes"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "Git"
  - "GitGutter"
  - "GitHub Flavored Markdown Preview"
  - "GitOpenChangedFiles"
  - "Golang Build"
  - "Highlight Trailing Whitespace"
  - "INI"
  - "Jinja2"
  - "Markdown Extended"
  - "MarkdownPreview"
  - "Package Control"
  - "Pretty JSON"
  - "Puppet"
  - "SublimeLinter"
  - "SublimeLinter-contrib-puppet-lint"
  - "SublimeLinter-contrib-staticcheck"
  - "SublimeLinter-contrib-yamllint"
  - "Terraform"
  - "Theme - Brogrammer"
  - "Theme - Monokai Pro"
  - "TrailingSpaces"
  - "Typora Markdown App (OSX)"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
