---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/mvilain/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/vilain/dotfiles
dotfiles_files:
  - .aliases
  - .exports
  - .exrc
  - .inputrc
  - .vimrc
  - .zshrc
  - robbyrussell.zsh-theme
  - xero

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - aria2
  - autoconf
  - autoconf-archive
  - automake
  - bash
  - binsider
  - bison
  - bitwarden-cli
  - brotli
  - btop  # also installs isl, libmpc, gcc
  - ca-certificates
  - cfssl
  - cheat
  - cmake
  # - cmake-docs # 11/2/23 python-packaging won't compile python 3.12 version
  - coreutils
  - curl
  - cyme
  - dateutils
  - dc3dd
  - docker-machine
  - docutils
  - electerm
  - envconsul
  - findutils
  - fping
  - fzf
  - gawk
  - gdbm
  - gettext
  - gitup
  - git-interactive-rebase-tool
  - glances
  - gmp
  - gpg
  - gpg2
  - gpg-tui
  - gpgme
  - go
  - go-bindata
  - helm
  - htop
  - intltool
  - iproute2mac
  - jq
  - kops
  - kubernetes-cli
  - libevent
  - libidn2
  - libnghttp2
  - libpng
  - libssh2
  - libtool
  - libunistring
  - libusb
  - libyaml
  - lnav
  - logrotate
  - lynx
  - lzip
  - m4
  # - mcrypt  10/28/22 deprecated
  - mhash
  - minikube
  - mtr
  - mutt
  - mpdecimal
  - mpfr
  - ncurses
  - nginx
  - nmap
  - oniguruma
  - openldap
  - opentofu  # 4/30/24 replacement for terraform
  - openssl@1.1
  - openssl@3
  - p7zip
  - pcre
  - pcre2
  - pkg-config
  - pinentry
  - pinentry-mac
  - popt
  - pstree
  # - python@3.10  # 4/3/24 python3.10 installed via MacOS
  - python@3.11
  - python@3.12
  - python@3.13
  - rbenv
  - re2c        # 11/29/24 or php 8.4+ compile/install since brew's php requires broken stuff
  - rclone
  - kapitainsky-rclone-browser
  - readline
  - ripgrep
  - rtmpdump
  - ruby-build
  # - ruby@2.7 # 5/15/23 ruby@2.7 deprecated
  # https://forge.rust-lang.org/infra/other-installation-methods.html
  # - rust # 3/16/23 use 'curl https://sh.rustup.rs -sSf | sh' instead of brew
  - six
  # - sphinx-doc   # 11/2/23 requires python-packages which won't install on 10.15
  - sqlite
  - ssh-copy-id
  - staticcheck
  - superfile
  - terragrunt
  - tnftp
  - tnftpd
  - tree
  - utf8proc
  - watch
  - webp
  - wget
  - xz
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh
  - zstd

homebrew_taps:
  - 1password/tap
  - buo/cask-upgrade
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

# the following casks have been updated beyond 10.13
# and require at minimum MacOS 10.15 (Catalina)
homebrew_cask_apps_1015:
  - alfred
  - appcleaner
  # - chronycontrol   # 8/18/23 1.4.11 installs and starts daemons correctly
  - forklift        # 12/2/23 4.0.5 installs on 12+
  - mullvadvpn      # 7/4/23 2023.4 says it only installs on BigSur+
  - netiquette
  # - opera           # 11/21/24 V114.0.5282.222 last version supports 10.15
  - profind         # 12/24/22 1.8 last version that supports 10.13
  - steermouse      # 10/19/22 5.6 last version that supports 10.13
  - torguard        # 3/8/23 4.8.14 supports 10.13; 4.8.15 installs 4.8.14 on 10.13; 4.8.16 just fails
  - typora          # 3/8/23 1.5.8 last version that supports 10.13
  - hashicorp/vagrant  # 10/26/22 2.3 doesn't run on 10.13 -- missing gem google-protobuf
  - viscosity
  - whatsyoursign   # 5/26/23 v2.1 won't install

# since brew won't allow cask versions, use this to limit what can be installed
# casks that only run on MacOS Ventura or later
homebrew_cask_apps_12:
  - 1passwword       # 2/19/25 8.10.60 last version for 10.15+
  - awscli
  # - bartender      # 6/5/24 application sold to questionable company...use 5.0.48
  - bitwarden        # 1/20/25 2025.x only works on 11+
  - calibre          # 11/17/23 7.0 on 12+, 6.29 on Ventura, 6.11 on Catalina
  - drawio           # 1/8/25 V25.0.3 runs on MacOS 10.15; V26+ runs on 11+
  - grandperspective # 3.3 last version that supports 10.15 7/16/23
  - git              # 2.48 won't install on 10.15
  - google-cloud-sdk # 6/19/24 4op81 works on monterrey if ~/.config/gcloud/virtenv is cleared first
  - google-chrome    # 9/17/24 chrome < 129 won't run on 10.15
  - google-drive     # 6/7/24 91.0.2 last version that runs on catalina
  - istat-menus      # 7/31/24 7.x version runs on 11+; use istat-menus@6 cask for 10.15
  - launchcontrol    # 6/7/24 discontinued 10.15 support
  - obs              # 7/23/24 runs on 11+
  - openbao          # 7/14/24 replacement for vault
  - typora           # 2/19/25 1.9.4 runs on 11+
  - xrg              # 10/31/23 v3.2.1 runs on BigSur+

# casks that only run on MacOS Sonoma or later
homebrew_cask_apps_13:
  - authy                 # can install iOS on M1 instead w/ Reduced Security
  - carbon-copy-cloner    # 5/23/24 7.x only runs on Sonoma

# the following casks work on 10.15 as of 10/2/23
homebrew_cask_apps:
  - 1password-cli
  - a-better-finder-attributes
  - a-better-finder-rename
  - affinity-designer
  - affinity-photo
  - affinity-publisherspek
  - anki
  - app-tamer
  - audacity
  - audiobook-builder
  # - authy 3/19/24 authy desktop EOL
  - balenaetcher
  - brave-browser
  - busycal
  - busycontacts
  - coconutbattery
  - commander-one
  - cyberduck
  - dbeaver-community
  - default-folder-x
  - dropbox
  - easyfind
  - eloston-chromium
  - etrecheckpro
  - exiftool
  - firefox
  - fliqlo
  - floorp
  - github
  - google-web-designer
  - go2shell
  - gotomeeting
  - graphicconverter
  - icollections
  - imazing
  - intellij-idea
  - istat-menus@6
  - jitsi-meet
  - joplin
  - keka
  - keyboard-maestro
  - knockknock
  - mdimagesizemdimporter
  - mediahuman-youtube-downloader
  - meteorologist
  - neofinder
  - ngrok
  # - nvalt     # 8/7/24 package deprecated; installed by hand
  - pacifist
  - protonmail-bridge
  - proton-drive
  - proton-mail
  - protonvpn
  - rar
  - scrivener
  - sloth
  - smartmontools
  - sublime-merge
  - sublime-text
  - superduper
  - sync
  - Taskexplorer
  - tg-pro
  - the-unarchiver
  - tor-browser
  - usenapp
  - vlc
  - vuescan
  - webex # 6/18/23 43.6.x downloaded from web site linked with wrong libraries...use brew to update
  - whatroute
  - xquartz
  - yate
  - youtube-to-mp3
  - zenmap
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
# tldr is an abbreviated man page https://github.com/tldr-pages/tldr
pip_packages:
  - ansible
  - ansible-core
  - ansible-lint
  - asn1crypto
  - astroid
  - certifi
  - cffi
  - entrypoints
  - flake8
  - importlib-metadata
  - isort
  - lazy-object-proxy
  - mccabe
  - pip
  - platformdirs
  - protobuf
  - pycodestyle
  - pycparser
  - pyflakes
  - pylint
  - setuptools
  - six
  - Sphinx
  - sphinxcontrib-napoleon
  - tldr
  - toml
  - typed-ast
  - typing-extensions
  - urllib3
  - virtualenv
  - wheel
  - wrapt
  - yamllint
  - xattr
  - zipp
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "Alignment"
  - "Ansible"
  - "AutoFileName"
  - "BracketHighlighter"
  - "ChangeQuotes"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "Git"
  - "GitGutter"
  - "GitHub Flavored Markdown Preview"
  - "GitOpenChangedFiles"
  - "Golang Build"
  - "Highlight Trailing Whitespace"
  - "INI"
  - "Jinja2"
  - "Markdown Extended"
  - "MarkdownPreview"
  - "Package Control"
  - "Pretty JSON"
  - "Puppet"
  - "SublimeLinter"
  - "SublimeLinter-contrib-puppet-lint"
  - "SublimeLinter-contrib-staticcheck"
  - "SublimeLinter-contrib-yamllint"
  - "Terraform"
  - "Theme - Brogrammer"
  - "Theme - Monokai Pro"
  - "TrailingSpaces"
  # - "Typora Markdown App (OSX)"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
