#!/bin/bash
# update python modules 202202.20MeV
# updated to include virtualenv module 202206.22MeV
# removed python 3.7 202207.29MeV
# removed python2.7 upgrade 202210.16MeV
# added python3.10 and 3.11 installed by brew 202211.05MeV

[ $EUID -ne 0 ] && echo "not root" && exit


# echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
# echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> $(date) python2.7"
# echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
# python2.7 -m pip install --upgrade \
#   altgraph \
#   astroid \
#   backports.ssl-match-hostname \
#   bdist-mpkg \
#   certifi \
#   contextlib2 \
#   cycler \
#   docker-pycreds \
#   entrypoints \
#   enum34 \
#   funcsigs \
#   functools32 \
#   importlib-metadata \
#   ipaddress \
#   kiwisolver \
#   List \
#   macholib \
#   matplotlib \
#   mccabe \
#   modulegraph \
#   numpy \
#   pip \
#   py2app \
#   pyparsing \
#   pytz \
#   scandir \
#   scipy \
#   setuptools \
#   singledispatch \
#   six \
#   subprocess32 \
#   tqdm \
#   twine \
#   typing \
#   webencodings \
#   websocket-client \
#   wheel \
#   wrapt \
#   xattr \
#   yYAML \
#   zipp \
#   zope.interface


echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> $(date) python3.8"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
# 10/29/22 astroid 2.5.1 requires wrapt<1.13
python3.8 -m pip install --upgrade \
  asn1crypto \
  astroid \
  certifi \
  cffi \
  entrypoints \
  flake8 \
  importlib-metadata \
  isort \
  lazy-object-proxy \
  mccabe \
  pip \
  platformdirs \
  protobuf \
  pycodestyle \
  pycparser \
  pyflakes \
  pylint \
  setuptools \
  six \
  toml \
  typed-ast \
  typing-extensions \
  urllib3 \
  virtualenv \
  wheel \
  wrapt==1.12 \
  yamllint \
  xattr\
  zipp


# 2/16/22 installed ansible...generated with
# # python3.9 -m pip list | awk '!/Package|-----/{printf "\t\t%s \\\n",$1}'


echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> $(date) python3.9"
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
python3.9 -m pip install --upgrade \
  ansible ansible-core ansible-lint \
  asn1crypto \
  astroid \
  certifi \
  cffi \
  entrypoints \
  flake8 \
  importlib-metadata \
  isort \
  lazy-object-proxy \
  mccabe \
  pip \
  platformdirs \
  protobuf \
  pycodestyle \
  pycparser \
  pyflakes \
  pylint \
  setuptools \
  Sphinx sphinxcontrib-napoleon \
  six \
  toml \
  typed-ast \
  typing-extensions \
  urllib3 \
  virtualenv \
  wheel \
  wrapt \
  yamllint \
  xattr \
  zipp

for ver in python3.10 python3.11; do
  echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
  echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> $(date) ${ver}"
  echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
  ${ver} -m pip install --upgrade certifi pip PyYAML setuptools six wheel virtualenv
done